# Generated by Django 2.0 on 2018-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'commit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.IntegerField()),
                ('pic_route', models.CharField(blank=True, max_length=50, null=True)),
                ('included_date', models.DateField(blank=True, null=True)),
                ('pic_route2', models.CharField(blank=True, max_length=50, null=True)),
                ('store', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gorder',
            fields=[
                ('oid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('included_date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18)),
                ('included_date', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
