-- MySQL Script generated by MySQL Workbench
-- 05/19/18 19:14:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema site
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site` DEFAULT CHARACTER SET utf8 ;
USE `site` ;

-- -----------------------------------------------------
-- Table `site`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`goods` (
  `gid` CHAR(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1500) NULL DEFAULT NULL,
  `type` VARCHAR(15) NULL DEFAULT NULL,
  `price` INT(11) NOT NULL,
  `pic_route` VARCHAR(50) NULL DEFAULT NULL,
  `included_date` DATE NULL DEFAULT NULL,
  `pic_route2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`gid`),
  UNIQUE INDEX `gid` (`gid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`user` (
  `uid` CHAR(15) NOT NULL,
  `username` VARCHAR(18) NOT NULL,
  `password` VARCHAR(18) NOT NULL,
  `included_date` DATE NULL DEFAULT NULL,
  `email_address` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `uid` (`uid` ASC),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site`.`gorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`gorder` (
  `oid` CHAR(15) NOT NULL,
  `gid` CHAR(15) NOT NULL,
  `uid` CHAR(15) NOT NULL,
  `included_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`oid`),
  UNIQUE INDEX `oid` (`oid` ASC),
  UNIQUE INDEX `gid` (`gid` ASC),
  UNIQUE INDEX `uid` (`uid` ASC),
  CONSTRAINT `gorder_ibfk_1`
    FOREIGN KEY (`gid`)
    REFERENCES `site`.`goods` (`gid`),
  CONSTRAINT `gorder_ibfk_2`
    FOREIGN KEY (`uid`)
    REFERENCES `site`.`user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site`.`super_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`super_user` (
  `username` VARCHAR(18) NOT NULL,
  `password` VARCHAR(18) NOT NULL,
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
